list1=[]
print(list1)
list1.append("newspaper")
print(list1)
list1.insert(1,"cse")
print(list1)
list1.insert(2,"articles")
print(list1)
list1.extend(["dictionary","magazine","novel"])
print(list1)
list1.remove("newspaper")
print(list1)
list1.pop(1)
print(list1)
#indexing
print(list1[2])
print(list1[-1])
#slicing
print(list1[:])
print(list1[0:2])
#concardination
list2=["datascience,engineeringmaths,mechanicmaterials"]
print(list1+list2)

